# Generated by Django 3.2.8 on 2022-05-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_area_finalistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_finalistica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tb_equipo_ob_parc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_proposta', models.CharField(max_length=100)),
                ('objeto', models.CharField(max_length=100)),
                ('tipo_ob', models.CharField(max_length=100)),
                ('ds_situacao_proposta', models.CharField(max_length=100)),
                ('ano_emissao_ob', models.CharField(max_length=100)),
                ('nu_ob_siafi', models.CharField(max_length=100)),
                ('dt_ob_siafi', models.CharField(max_length=100)),
                ('vl_pago_ob_prop', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tb_equipo_saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=100)),
                ('nr_proposta', models.CharField(max_length=100)),
                ('tipo_saldo', models.CharField(max_length=100)),
                ('rotulo_conta', models.CharField(max_length=100)),
                ('banco_prop', models.CharField(max_length=100)),
                ('agencia_prop', models.CharField(max_length=100)),
                ('conta_prop', models.CharField(max_length=100)),
                ('dt_ult_pgto_prop', models.CharField(max_length=100)),
                ('dt_saldo_prop', models.CharField(max_length=100)),
                ('ds_secretaria', models.CharField(max_length=100)),
                ('vl_saldo_conta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tb_esfera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esfera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tb_municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_municipio', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tb_recebedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_recebedor', models.CharField(max_length=100)),
                ('razao_social_recebedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tb_tipo_objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_objeto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tb_uf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tb_equipo_ressarc',
            fields=[
                ('nr_proposta', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('PORTARIA_CANCELAMENTO', models.CharField(max_length=100)),
                ('DT_PORTARIA_CANCELAMENTO', models.CharField(max_length=100)),
                ('tipo_de_transferencia', models.CharField(max_length=100)),
                ('nr_portaria_habilitacao', models.CharField(max_length=100)),
                ('ano_portaria_habilitacao', models.CharField(max_length=100)),
                ('data_portaria_habilitacao', models.CharField(max_length=100)),
                ('valor_proposta', models.CharField(max_length=100)),
                ('valor_transferido', models.CharField(max_length=100)),
                ('valor_nao_transferido', models.CharField(max_length=100)),
                ('FK_area_finalistica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basedados.tb_area_finalistica')),
                ('FK_esfera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basedados.tb_esfera')),
                ('FK_municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basedados.tb_municipio')),
                ('FK_recebedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basedados.tb_recebedor')),
                ('FK_tipo_objeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basedados.tb_tipo_objeto')),
                ('FK_uf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basedados.tb_uf')),
            ],
        ),
    ]
